<?php

return [
    'filename' => 'yourcsvfilename.csv',
    'actions' => [
        'sliceBeginningRows' => 6,
        // headerIndex => newHeaderName
        'renameHeaders' => [
            3 => 'Auftraggeber'
        ],
        // remove row if column equals to a given value
        'removeRowIf' => [
            'Auftraggeber' => [
                'KREDITKARTENABRECHNUNG',
            ],
            'Verwendungszweck' => [
                'Tagessaldo',
            ],
            'Buchungstext' => [
                'Abschluss',
                'Entgeltinformation'
            ],
        ],
        // can be the headerIndex or the headerName
        'removeColumnByHeaders' => [
            'Wertstellung',
            'Buchungstext',
            'BLZ',
            8,
            'Mandatsreferenz',
            'Kundenreferenz',
            ''
        ],
        // create a new hash column which contains a hash generated by the following headerIndices
        'hashByHeaders' => [
            0,
            3,
            5,
            7
        ],
        'addColumns' => action('addColumns', 'dkb_categories')
    ]
];